### PR TITLE
license header

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Added a regex to remove `/*\n * Copyright ... */` before processing, LMK what you think :)

**Comment by nevillelyh** [comment]
It turns out more complex than that. I probably need to remove it in to compilation unit too.

**Review by guillaumebort — CHANGES_REQUESTED** [review]
Looks good but why looking specifically for 'Copyright' ? Perhaps it would be better and simpler to just skip anything (all lines) before the `// Example:` marker?

**Comment by nevillelyh** [comment]
Sure, so just remove the starting `/* ... */`?

**Comment by guillaumebort** [comment]
Either that or just skip everything before the line starting by `// Example:`. Something like

```scala
lines.dropWhile(line => !line.startsWith("// Example:"))
```

**Comment by nevillelyh** [comment]
Fixed. The offset handling is a bit ugly, but can't think of a better way.

**Review by guillaumebort — APPROVED** [review]
Cool thanks!

**Pull request merged**
